[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
noise = { version = "0.8", default-features = false }

[features]
default = []
